version: "3.8"
services:
  db:
    image: postgres:15
    container_name: db_course_work
    restart: always
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata: